name: Deploy

on:
  push:
    branches: [main]

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: Deploy site
      steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Deploy
            uses: Dylan700/sftp-upload-action@latest
            with:
              server: ${{secrets.FTP_SERVER}}
              username: ${{secrets.FTP_USERNAME}}
              password: ${{secrets.FTP_PASSWORD}}
              port: 22
              uploads: |
                ./src => ./
              ignore: |
                *.git
                */**/*git*
