name: Deploy

on:
  push:
    branches: [main]

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: Deploy site
      steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Download tailwindcss
            run: curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64

          - name: Install tailwindcss
            run: chmod +x tailwindcss-linux-x64 && mv tailwindcss-linux-x64 tailwindcss

          - name: Build tailwindcss
            run: ./tailwindcss -i tailwind.css -o src/styles.css --minify

          - name: Deploy
            uses: Dylan700/sftp-upload-action@latest
            with:
              server: ${{secrets.FTP_SERVER}}
              username: ${{secrets.FTP_USERNAME}}
              password: ${{secrets.FTP_PASSWORD}}
              port: 22
              uploads: |
                ./src => ./
              ignore: |
                *.git
                */**/*git*
